project:
  type: book

book:
  title: "Automated Reasoning in Python"
  author: "Philip Zucker"
  date: "7/5/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - term.qmd
    - lcf.qmd
    - kb.qmd
    - references.qmd

bibliography: references.bib

format:
  html:

    theme:       
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt


#    minimal: true
